# Custom Server Port: 8081
server:
  port: 8081

# Spring Boot Configuration
spring:
  application:
    name: RequestReplyDemo

  # Spring Kafka Settings
  kafka:
    listener:
      missing-topics-fatal: false

    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0
      batch-size: 16384  # 16kB
      buffer-memory: 33554432
      properties:
        linger.ms: 1

    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      auto-commit-interval: 100ms
      properties:
        session.timeout.ms: 15000
        spring:
          json:
            trusted:
              packages: com.karaya.kafka.model

# Kafka Custom Configuration
kafka:
  group:
    id: RequestReplyDemoGroup
  request:
    topic: StudentRequest
  reply:
    topic: StudentReplyResult

# Log4j Configuration Path
logging:
  config: classpath:log4j2-spring.xml